### ISSUE TITLE
NodeJS Quick Start - newbie experience - Python pre-req on Windows?

### ISSUE THREAD

**Issue by lisheeghan** [maidsafe/dev_website#20]
Hi, just blindly following the "Start Developing" NodeJS instructions, I encountered an error - looks like Python should perhaps be listed as a pre-req for developing on Windows 10?

    C:\maidsafe\safe_examples\safe_app_electron_quick_start> npm install @maidsafe/safe-node-app --save
    npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
    npm WARN deprecated natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.

    > ref@1.3.5 install C:\maidsafe\safe_examples\safe_app_electron_quick_start\node_modules\ref
    > node-gyp rebuild

    C:\maidsafe\safe_examples\safe_app_electron_quick_start\node_modules\ref> if not defined npm_config_node_gyp (node "C:\Users\lis\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\lis\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
    gyp ERR! configure error
    gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
    gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\lis\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
    gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\lis\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
    gyp ERR! stack     at C:\Users\lis\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
    gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
    gyp ERR! System Windows_NT 10.0.16299
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lis\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\maidsafe\safe_examples\safe_app_electron_quick_start\node_modules\ref
    gyp ERR! node -v v8.11.1
    gyp ERR! node-gyp -v v3.6.2
    gyp ERR! not ok
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! ref@1.3.5 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the ref@1.3.5 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\lis\AppData\Roaming\npm-cache\_logs\2018-04-26T11_20_57_652Z-debug.log

When I installed Python 2.7.14 - the above error disappeared.  Perhaps also worth listing the minimum versions for each pre-req?

**Comment by hunterlester** [comment]
@lisheeghan Yes, thanks for this reminder.
Out of curiosity did you install Python directly from [python.org](https://www.python.org) or did you use the NPM [windows-builds-tools](https://www.npmjs.com/package/windows-build-tools) package?

**Comment by lisheeghan** [comment]
@hunterlester - I used python.org (I also accepted the option to add it to the PATH).

**Comment by hunterlester** [comment]
@lisheeghan Did you have Microsoft Visual Studio build tools previously installed? That's something else that's handled by the `windows-build-tools` module.

**Comment by lisheeghan** [comment]
@hunterlester - just saw your comment - actually in the end, I had independently switched over to the windows-build-tools (https://github.com/felixrieseberg/windows-build-tools) - as suggest by @shane in one of his forum posts.

I was hitting some pretty strange 2nd-pass build errors - and the app didn't work properly at all, with various "weakref.node" binding errors in the console output.

It was a battle and newbies could be easily discouraged at step 1.  Perhaps the window-build-tools instructions should also be included in the notes (for Windows users).

**Comment by hunterlester** [comment]
@lisheeghan This is helpful. Was the `weakref.node` error cleared up after installing `windows-build-tools`?
I was wondering if you also had to run `npm rebuild --runtime=electron --target=<electron version> --disturl=https://atom.io/download/atom-shell --build-from-source`  [src](https://github.com/hunterlester/safe-app-base/blob/master/package.json#L8)?
Although I'm thinking that you shouldn't need to rebuild, as this is already taken care of when `@maidsafe/safe-node-app` is installed.

**Comment by bochaco** [comment]
This should be now fixed with PR #34.
