### ISSUE TITLE
Content as Markdown

### ISSUE THREAD

**Issue by chpio** [maidsafe/dev_website#26]
Is there a reason to not format the content as Markdown/CommonMark? This would make editing much easier. You could also use inline html for "fancy" things.

edit1: As you'r using react this [wouldn't work](https://github.com/rexxars/react-markdown#inline-html-is-broken) with inline html and the [react-markdown](https://github.com/rexxars/react-markdown). But you could add an additional build step that would convert markdown files to react components, similar to what you'r doing right now with the hardcoded links to the content "variables" but automagically.

edit2: https://github.com/nozzle/react-static/tree/master/examples/markdown

**Comment by chpio** [comment]
im [working on this](https://github.com/chpio/maidsafe_dev_website)

i was thinking that rendering to string and outputting with jdown is kinda lame, so i made [rehype-react-serialized](https://github.com/chpio/rehype-react-serialized) (converts [hast](https://github.com/syntax-tree/hast) to a "serialized" react format) and [render-react-serialized](https://github.com/chpio/render-react-serialized) (renders the "serialized" format to react).
* it's a small format (compered to hast)
* you can do all the work (code highlighting) at buildtime
* render-react-serialized is minimalist (the library needed at runtime)
* no need to parse html and "convert" it to react as the format is pretty much equal to the react [createElement format](https://reactjs.org/docs/react-api.html#createelement)

**Comment by hunterlester** [comment]
I think your proposal for Markdown was a necessity, thank you. There was a commit 3 days ago for it: https://github.com/maidsafe/dev_website/commit/9e3ac01e2c3d8a35505903f832840f974fd84f26

Let us know what you think of this approach.

**Comment by chpio** [comment]
published to npm:
* https://www.npmjs.com/package/rehype-react-serialized
* https://www.npmjs.com/package/render-react-serialized
