### ISSUE TITLE
Update RFC section

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/dev_website#44]
Currently the DevHub has a list of some RFC's at the bottom of this page https://hub.safedev.org/core_technology/

With the proposal of a new process its timely to review if how its presented on DevHub is useful for readers.

**Comment by david-maidsafe** [comment]
Looking at updating this as part of me little review.

**Comment by david-maidsafe** [comment]
Removed mention of specific RFCs and pointed to repo.

https://github.com/maidsafe/dev_website/pull/88/
