### ISSUE TITLE
Change *Docs* link in footer from sn.org to https://docs.maidsafe.net/

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/dev_website#47]
Causing confusion - e.g. https://forum.safedev.org/t/mutable-data-permissions-can-a-mutable-data-structure-be-set-append-only-to-everyone-including-the-owner/2023/3?u=nadia

**Comment by nadiaburborough** [comment]
A new page is to be drafted which gives links to the sites which automatically generates the documentation from our code, and instructional/informative information to be written with it.

**Comment by david-maidsafe** [comment]
related:(https://github.com/maidsafe/safe_browser/issues/346)

**Comment by david-maidsafe** [comment]
change made - awaiting PR

**Comment by david-maidsafe** [comment]
Resolved in [#78](https://github.com/maidsafe/dev_website/pull/78) & [#83](https://github.com/maidsafe/dev_website/pull/83)
