### ISSUE TITLE
Site doesn't load on IE11

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/dev_website#59]
Old tech yeah so not a priority, but might be a simple react fix to get the site at the very least displaying.
@shankar2105 managed to solve a similar issue with safenetwork.tech.

![image](https://user-images.githubusercontent.com/37112040/45765059-05ff4b00-bc2c-11e8-8c46-d47b85c80154.png)

Win10 VM, IE 11.611.162990.0
Works fine on Edge

**Comment by frabrunelle** [comment]
The site should be working fine in IE11 now.
