### ISSUE TITLE
Links not clickable on StartDeveloping/Platform page

### ISSUE THREAD

**Issue by ashwinkumar6** [maidsafe/dev_website#84]
Steps to reproduce
- Go to homepage `https://hub.safedev.org/`
- Go to `Platform` page by clicking on the `SartDeveloping` link on the title bar and then click on any platform `Android`, `Xamairn` ,`.Net`, `Web` `Nodejs` 
- None of links `StartDeveloping`  `Documents` `CoreTechnology` `Discover` `Community` in title bar are clickable

**Comment by david-maidsafe** [comment]
https://github.com/maidsafe/dev_website/pull/88/commits/4c14ce1dd42db07c97e5ffa7c7e8c172657f51c5

**Comment by david-maidsafe** [comment]
resolved in https://github.com/maidsafe/dev_website/pull/88/
