### ISSUE TITLE
Side menu scrolls with body of page.

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/dev_website#90]
**Steps to reproduce:**
1. Build dev_website from `feat` branch of David's fork: https://github.com/david-maidsafe/dev_website/tree/feat
2. Go to platform page.
3. Scroll page.

**Expected:**
Side menu is static, does not scroll with rest of page. Eg on current page:
![image](https://user-images.githubusercontent.com/44327924/55090760-91f4a280-50a7-11e9-86d7-61ea145f576c.png)

**Actual:**
Side menu is fixed at the top of the body of the content and scrolls as rest of the page scrolls:
![image](https://user-images.githubusercontent.com/44327924/55090736-843f1d00-50a7-11e9-901c-7526fb7ed015.png)

**Comment by david-maidsafe** [comment]
Addressed by commit:
https://github.com/maidsafe/dev_website/pull/88/commits/4c14ce1dd42db07c97e5ffa7c7e8c172657f51c5

**Comment by calumcraig** [comment]
Retested after above fix applied and is now working as expected - the side menu remains static while the main body of the page scrolls:
![image](https://user-images.githubusercontent.com/44327924/55151345-f6663f00-5145-11e9-9424-a05adaf576ef.png)
Closing bug and moving to done.
